PROJECTS = [
    {"id":"bot_stress","number":"01","title":"RUN BOT TEST",
     "subtitle":"20 scenarios + 6 follow-up; JSON validation and cognitive stress metrics.",
     "endpoint":"bot_new","kind":"Human–AI","status":"LIVE"},
    {"id":"human_ai","number":"02","title":"HUMAN ↔ AI PAIR",
     "subtitle":"Human answers first, then the participant's personalized AI.",
     "endpoint":"hai_new","kind":"Human–AI","status":"LIVE"},
    {"id":"benchmarks","number":"03","title":"EXTERNAL BENCHMARKS",
     "subtitle":"Models against authorized human distributions and research benchmark packs.",
     "endpoint":"benchmarks","kind":"Benchmark","status":"LIVE"},
    {"id":"history","number":"04","title":"HISTORY INTERVENTION",
     "subtitle":"Same model and target, controlled difference in prior history.",
     "endpoint":"history_probe.new_pair","kind":"Causality","status":"LIVE"},
    {"id":"grp","number":"05","title":"COGNITIVE DYNAMICS / GRP",
     "subtitle":"32-step randomized reset-washout association experiment on the shared participant identity.",
     "endpoint":"universe_grp.home","kind":"Human","status":"INTEGRATED"},
    {"id":"observer_wapi","number":"06","title":"OBSERVER WAPI",
     "subtitle":"Response-timing benchmark: person, history, state, input and person×nonverbal interaction.",
     "endpoint":"universe_observer.wapi_home","kind":"Dataset","status":"ENGINE"},
    {"id":"mor_observer","number":"07","title":"MOR OBSERVER",
     "subtitle":"State / geometry / corridor / transition research exports from the observer engine.",
     "endpoint":"universe_observer.mor_home","kind":"MOR","status":"ENGINE"},
    {"id":"mor_mesh","number":"08","title":"MOR MESH FIELD LAB",
     "subtitle":"Android two-node encrypted mesh field tests with verified HELLO, delivery and ACK lifecycle.",
     "endpoint":"universe_mesh.home","kind":"Network","status":"FIELD"},
]
